# Generated by Django 5.1.4 on 2024-12-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=200)),
                ('publishing_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
